language: node_js
version: "= 1.0"
os:
  - linux

node_js:
  - 8
  - 10
  - 12
  - 13

before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - npm ci
  - npm run build
  - npm run test

deploy:
  provider: npm
  email: tom@carrio.dev
  api_key: ${NPM_TOKEN}
  edge: true
  on:
    branch: master
    node: '12'
